
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      data-source-properties:
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true


  logging:
  level:
    org.hibernate.SQL: debug

